set_property -dict {PACKAGE_PIN H4   IOSTANDARD LVDS_25}  [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN G4   IOSTANDARD LVDS_25}  [get_ports sys_clk_n]

# defined in clk_wiz_0.xdc
# create_clock -period 5.000 -name sysclk [get_ports sys_clk_p]

set_property -dict {PACKAGE_PIN D19  IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

set_property -dict {PACKAGE_PIN C14  IOSTANDARD LVCMOS33} [get_ports "PCout[0]"]
set_property -dict {PACKAGE_PIN C15  IOSTANDARD LVCMOS33} [get_ports "PCout[1]"]
set_property -dict {PACKAGE_PIN D14  IOSTANDARD LVCMOS33} [get_ports "PCout[2]"]
set_property -dict {PACKAGE_PIN D15  IOSTANDARD LVCMOS33} [get_ports "PCout[3]"]
set_property -dict {PACKAGE_PIN B15  IOSTANDARD LVCMOS33} [get_ports "PCout[4]"]
set_property -dict {PACKAGE_PIN B16  IOSTANDARD LVCMOS33} [get_ports "PCout[5]"]
set_property -dict {PACKAGE_PIN C13  IOSTANDARD LVCMOS33} [get_ports "PCout[6]"]
set_property -dict {PACKAGE_PIN B13  IOSTANDARD LVCMOS33} [get_ports "PCout[7]"]
set_property -dict {PACKAGE_PIN A15  IOSTANDARD LVCMOS33} [get_ports "PCout[8]"]
set_property -dict {PACKAGE_PIN A16  IOSTANDARD LVCMOS33} [get_ports "PCout[9]"]
set_property -dict {PACKAGE_PIN A13  IOSTANDARD LVCMOS33} [get_ports "PCout[10]"]
set_property -dict {PACKAGE_PIN A14  IOSTANDARD LVCMOS33} [get_ports "PCout[11]"]
set_property -dict {PACKAGE_PIN B17  IOSTANDARD LVCMOS33} [get_ports "PCout[12]"]
set_property -dict {PACKAGE_PIN B18  IOSTANDARD LVCMOS33} [get_ports "PCout[13]"]
set_property -dict {PACKAGE_PIN C18  IOSTANDARD LVCMOS33} [get_ports "PCout[14]"]
set_property -dict {PACKAGE_PIN C19  IOSTANDARD LVCMOS33} [get_ports "PCout[15]"]
set_property -dict {PACKAGE_PIN B20  IOSTANDARD LVCMOS33} [get_ports "PCout[16]"]
set_property -dict {PACKAGE_PIN A20  IOSTANDARD LVCMOS33} [get_ports "PCout[17]"]
set_property -dict {PACKAGE_PIN A18  IOSTANDARD LVCMOS33} [get_ports "PCout[18]"]
set_property -dict {PACKAGE_PIN A19  IOSTANDARD LVCMOS33} [get_ports "PCout[19]"]
set_property -dict {PACKAGE_PIN D20  IOSTANDARD LVCMOS33} [get_ports "PCout[20]"]
set_property -dict {PACKAGE_PIN C20  IOSTANDARD LVCMOS33} [get_ports "PCout[21]"]
set_property -dict {PACKAGE_PIN C22  IOSTANDARD LVCMOS33} [get_ports "PCout[22]"]
set_property -dict {PACKAGE_PIN B22  IOSTANDARD LVCMOS33} [get_ports "PCout[23]"]
set_property -dict {PACKAGE_PIN B21  IOSTANDARD LVCMOS33} [get_ports "PCout[24]"]
set_property -dict {PACKAGE_PIN A21  IOSTANDARD LVCMOS33} [get_ports "PCout[25]"]
set_property -dict {PACKAGE_PIN E22  IOSTANDARD LVCMOS33} [get_ports "PCout[26]"]
set_property -dict {PACKAGE_PIN D22  IOSTANDARD LVCMOS33} [get_ports "PCout[27]"]
set_property -dict {PACKAGE_PIN G17  IOSTANDARD LVCMOS33} [get_ports "PCout[28]"]
set_property -dict {PACKAGE_PIN G18  IOSTANDARD LVCMOS33} [get_ports "PCout[29]"]
set_property -dict {PACKAGE_PIN H17  IOSTANDARD LVCMOS33} [get_ports "PCout[30]"]
set_property -dict {PACKAGE_PIN H18  IOSTANDARD LVCMOS33} [get_ports "PCout[31]"]
